{% set name = "inaSpeechSegmenter" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | lower }}-{{ version }}.tar.gz
  sha256: 5bcc5d759957b70c70cf0b5fbd89cfd35c62f1ff5ebc5466ce4c3b187d81b636

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1
  noarch: python
  string: "{{ target_os }}_pyh{{ PKG_HASH }}_{{ PKG_BUILDNUM }}"

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }},<3.13
    - ffmpeg
    - tensorflow >2.4   #not avalaible yet on py313 and avalaible windows versions are for older unsupported python version
    - numpy
    - pandas
    - scikit-image
    - pyannote.core
    - matplotlib-base
    - pyro4
    - pytextgrid
    - pysoundfile
    - onnxruntime *=*_cuda  # [linux]
    - onnxruntime  # [osx]
    - __{{ target_os }}

test:
  imports:
    - inaSpeechSegmenter
  commands:
    - pip check
    - ina_speech_segmenter.py --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ina-foss/inaSpeechSegmenter
  summary: CNN-based audio segmentation toolkit. Does voice activity detection, speech detection, music detection, noise detection, speaker gender recognition.
  license: MIT
  license_file: LICENSE
  description: |
    inaSpeechSegmenter is a CNN-based audio segmentation toolkit suited to the tasks of Voice Activity Detection and Speaker Gender Segmentation.
    It splits audio signals into homogeneous zones of speech, music and noise. Speech zones are split into segments tagged using speaker gender (male or female). 
    Male and female classification models are optimized for French language since they were trained using French speakers (acoustic correlates of speaker gender are language dependent). 
    Zones corresponding to speech over music or speech over noise are tagged as speech. Singing voice is tagged as music.

extra:
  recipe-maintainers:
    - HeavyTony2
